name: legacy-ui-checks
on: [pull_request, push]
permissions:
  contents: read
  pull-requests: read
jobs:
  tests:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all }}
    strategy:
      fail-fast: false
      matrix:
        php: [8.1]
        paths: [Modules, Services]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          args: --no-interaction --no-progress --ignore-platform-reqs

      - uses: php-actions/phpstan@v3
        with:
          php_version: ${{ matrix.php }}
          error_format: table
          configuration: CI/PHPStan/legacy_ui.neon
          path: ${{ matrix.paths }}
          autoload_file: libs/composer/vendor/autoload.php
          memory_limit: -1
          args: --no-progress --no-interaction
